name: Docker Image CI
on:
  push:
    tags: [ 'fe*.*.*', 'api*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Use tag
        run: echo ${{ steps.tag.outputs.tag }}

      - name: Check Repo Names
        run: |
          echo ${{ secrets.DOCKERHUB_FRONTEND_REPO }}
          echo ${{ secrets.DOCKERHUB_BACKEND_REPO }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image (FrontEnd)
        if : ${{ startsWith(steps.tag.outputs.tag, 'fe') && secrets.DOCKERHUB_FRONTEND_REPO }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_FRONTEND_REPO }}:release-${{ steps.tag.outputs.tag }} ./ --no-cache
          docker tag ${{ secrets.DOCKERHUB_FRONTEND_REPO }}:release-${{ steps.tag.outputs.tag }} ${{ secrets.DOCKERHUB_FRONTEND_REPO }}:latest
          docker push ${{ secrets.DOCKERHUB_FRONTEND_REPO }}:release-${{ steps.tag.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_FRONTEND_REPO }}:latest

      - name: Build & Push Docker Image (BackEnd)
        if : ${{ startsWith(steps.tag.outputs.tag, 'api') && env.DOCKERHUB_BACKEND_REPO }}
        run: |
          cd api
          docker build -t ${{ secrets.DOCKERHUB_BACKEND_REPO }}:release-${{ steps.tag.outputs.tag }} ./ --no-cache
          docker tag ${{ secrets.DOCKERHUB_BACKEND_REPO }}:release-${{ steps.tag.outputs.tag }} ${{ secrets.DOCKERHUB_BACKEND_REPO }}:latest
          docker push ${{ secrets.DOCKERHUB_BACKEND_REPO }}:release-${{ steps.tag.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_BACKEND_REPO }}:latest