name: Docker Image CI
on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ feature/* ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: bart2001
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: echo tag name
        run: echo ${{ github.event.release.tag_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}